---
abstract: 'Authenticate with CAS servers as a browser'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authen-CAS-External
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTML::Form: 5.817
  HTTP::Status: 5.817
  LWP::UserAgent: 5.819
  Moose: 0.77
  Moose::Role: 0.77
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.08
  MooseX::Types::Moose: 0
  Scalar::Util: 1.14
  URI: 1.22
  URI::QueryParam: 0
  namespace::clean: 0.04
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
